### ISSUE TITLE
Add Support for utf-8 characters

### ISSUE THREAD

**Issue by RajChanchal** [lauriro/json-lite#9]
When I used this extension today on Safari, for Arabic text strings I could only see '????????' instead of actual words. Then I tried 'JSONView' extension and it worked fine. But I love the colour scheme and clearity you have added. Thumbs up and expecting this change soon.

**Comment by lauriro** [comment]
Could you provide an example json? My utf-8 test file works.

**Comment by RajChanchal** [comment]
Sure, attached is a file with the response json.
When it's fine, it should appear like following:
<img width="423" alt="screen shot 2017-04-13 at 3 49 07 pm" src="https://cloud.githubusercontent.com/assets/7058465/25003521/d6bb91f4-2060-11e7-8ef1-109d875db85a.png">

[sample.json.zip](https://github.com/lauriro/json-lite/files/919389/sample.json.zip)

**Comment by zydeco** [comment]
This happens because the plugin uses Safari's default encoding if it is not sent by the server, which is ISO Latin 1 unless it has been changed (maybe this depends on the locale?).
For JSON, the default encoding should be UTF-8.

From [RFC 7159 - The JavaScript Object Notation](https://tools.ietf.org/html/rfc7159#section-8.1):

> JSON text SHALL be encoded in UTF-8, UTF-16, or UTF-32.  The default
   encoding is UTF-8, and JSON texts that are encoded in UTF-8 are
   interoperable in the sense that they will be read successfully by the
   maximum number of implementations; there are many implementations
   that cannot successfully read texts in other encodings (such as
   UTF-16 and UTF-32).

A workaraound is to change the default encoding in Safari's preferences (in Advanced) to “Unicode (UTF-8)”

**Comment by RajChanchal** [comment]
Thanks for the answer, I don't then how JSONView does it fine..
